apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090        
      targetPort: 9090  
      nodePort: 30090   
